@startuml

Title Cupcake Projekt

State startside
State opretBurer
State logUd
State bestillinger
State indkøbskurv
State betaling


[*] -> startside
startside --> startside : retur
startside --> bestillinger : log på
bestillinger --> indkøbskurv : går til indkøbskurvcart
indkøbskurv --> bestillinger : tilbage til bestillinger
indkøbskurv --> betaling : til betaling
betaling --> bestillinger : betaling gennemført
betaling --> logUd
bestillinger --> logUd
startside --> logUd : log ud

startside --> opretBurer : opret burer
opretBurer --> bestillinger : opret burer

@enduml
